### ISSUE TITLE
Bulk delete records

### ISSUE THREAD

**Issue by wykhuh** [collectiveaccess/providence#1044]
For the GraphQL API, it would be good to let developers who are testing out the import scripts to delete multiple items.  

Possible options
- Pass in multiple ids or a range of ids
- Drop all records that were created after a certain time.
- Truncate the table to delete all the records. 

Caveat
- Might need to add more security to prevent bulk deleting records on a live site.

**Comment by collectiveaccess** [comment]
Will do!

**Comment by wykhuh** [comment]
@collectiveaccess Can we update the batch delete method to delete all list items that belong to a certain list?

**Comment by collectiveaccess** [comment]
Yes, definitely.

**Comment by collectiveaccess** [comment]
Added new list parameter to edit service `truncate` mutation. If set it'll truncate the specified list, subject to optional `date` (last modification date) and `types` parameters. You might combine `list` with `date` to get rid of list items created after a certain date/time. Since types are rarely used with list items, the `types` option is less useful, but not useless, so I left it in place.

Note that if list is set, and setting for `table` is ignored. It's always assumed to be `ca_list_items`.

Example:
   ```
     mutation {
            truncate(
                    list:"chemical_deterioration", fast: true
            ) { 
                    id
                    table,
                    idno,
                    changed,
                    errors {code, message, bundle},
                    warnings { message, bundle}
            }
        }
```
