### ISSUE TITLE
OAI PMH limitToModifiedOn does not work

### ISSUE THREAD

**Issue by karbecker** [collectiveaccess/providence#331]
Hi!

We noticed (we _think_ we noticed) another error in CA’s OAI PMH Service. 

When using the `listRecords` verb we need to be able to limit the response by modification date. Using `&from=2018-05-23&until=2018-05-24` does not work, we instantly get back object records with `<datestamp>2018-05-16T09:39:48Z</datestamp>` and so on. 

We noticed that in `OAIPMHService.php` in Line 512:

https://github.com/collectiveaccess/providence/blob/4a3db6adf77c06a952d321a8068c4e637761fae1/app/lib/ca/Service/OAIPMHService.php#L512

`'limitToModifiedOn' => $vs_range,` gets passed on to `SearchEngine.php` where in turn `limitToModifiedOn` appears only once in a commented help line. Nevertheless, filtering by modification date does not work at our end and it would be great if you could look into that as it is need for a functional OAI-PMH interface.

Thanks!

**Comment by karbecker** [comment]
Hi, has anyone had the same problem?

**Comment by collectiveaccess** [comment]
Not that I've heard of. Did you create a JIRA for it? If not please do so an I'll try to replicate this issue this week.

**Comment by karbecker** [comment]
I’ll create one tomorrow. Thanks!

**Comment by karbecker** [comment]
I created [PROV-2516](http://clangers.collectiveaccess.org/jira/browse/PROV-2516)

**Comment by collectiveaccess** [comment]
This is fixed in the develop branch.

**Comment by karbecker** [comment]
Unfortunately that does not work, doing so kills the OAI-PMH Service completely. I see that you changed the path from `/app/lib/ca/Service` to `/app/lib/Service`, does this have anything to do with it? 

Anyways, can you tell if the next stable release containing the fix will be up in within a short time? If not, would you mind looking into using this fix with 1.7.6 stable? Thanks!

**Comment by collectiveaccess** [comment]
Yes this is done against current develop code. The paths have changed.

**Comment by karbecker** [comment]
So is this the issue that prevents me from using the changed OAI Provider in 1.7.6 or do you think that I should be able to use it? Just asking if you think I should keep trying or if I need to wait for the next stable release. 

Thanks!

**Comment by collectiveaccess** [comment]
You can try changing the paths in the file to ones compatible with 1.7.6. There are only two:

These:

require_once(__CA_LIB_DIR__."/Service/BaseService.php");
require_once(__CA_LIB_DIR__."/Export/OAIPMH/OaiIdentifier.php");

should be changed to these:

require_once(__CA_LIB_DIR__."/ca/Service/BaseService.php");
require_once(__CA_LIB_DIR__."/ca/Export/OAIPMH/OaiIdentifier.php");

**Comment by karbecker** [comment]
Unfortunately this does not work.

**Comment by aruijmen** [comment]
Hi,
[OAIPMHService.zip](https://github.com/collectiveaccess/providence/files/2383242/OAIPMHService.zip)

Can you do a test with the following OAIPMHService.php?
(in the original place of the current master (app/lib/ca/Service).
In this file I've incorporated (some/but not all) changes of the develop-branch.
I looked into the file after discovering that the 'dont_enforce_access_settings'-parameter wasn't working as it should (verb=ListIdentifiers gave all the records back, although no access was allowed).
Kind regards
Anita  
PS: to attach a-php file I needed to zip it

**Comment by karbecker** [comment]
Hi @aruijmen thanks for the file! When I’m using it, my OAI-PMH Service does not show any objects at all, regardless of which verb I’m using. Our OAI Service is accessible at 

https://bildpostkarten.uos.de/backend/service.php/OAI/bpk 

and it’s working without any specified date range:

https://bildpostkarten.uos.de/backend/service.php/OAI/bpk?verb=ListRecords&metadataPrefix=epicur

but not when using a date range:

https://bildpostkarten.uos.de/backend/service.php/OAI/bpk?verb=ListRecords&metadataPrefix=epicur&from=2018-01-01T00:00:01Z&until=2018-09-21T23:59:59Z

(a lot of objects have been modiefied in the last 9 months).

**Comment by collectiveaccess** [comment]
Hi,

So these links are with the stock 1.7.6 code, right?

**Comment by karbecker** [comment]
No, that’s @aruijmen’s OAI Service.

**Comment by aruijmen** [comment]
Hi @karbecker 
Can you send me a copy of your oai_provider.conf file (in app/conf/local)?
Check dont_enforce_access_settings = 0 in this file.
Check if your records access is set to the value public_access_settings = [1]

Hi @collectiveaccess 
This is indeed against the 1.7.6. master.
I'm new to oaipmh, but we noticed that there was an isssue with the parameter dont_enforce_access_settings = 0. 
When using the oai Repository explorer (http://re.cs.uct.ac.za/) to test our setup, we noticed that 
although we used this parameter, we always got all the records, and all the collections back.
But by incorporating some changes from the file in the development branch, it seems to be working fine now. Only collections with access=1 (=public access) and records with access = 1 are returned.
I also tried it with from=yyyy-mm-dd and until=yyyy-mm-dd, and this worked for me.
I still need to do some testing because there are still some errors using a validator.

**Comment by aruijmen** [comment]
Hi @karbecker 
Concerning your oai_provider.conf:
- there is a "," missing at the end of line 18 (after title_facet)
- about title_facet: what is it referring to in Browse.conf? 
- It is not logical that with public_access_settings = [1] that [1] is repeated in privileged_access_settings = [1,2], your record is either public or not (so remove the 1 in priviliged_access_settings)

I noticed indeed that in my case the from and until returned all my public records.
Debugging the php-programs I found that the following sql-statement was executed:
SELECT DISTINCT ca_objects.object_id
FROM ca_objects
INNER JOIN ca_change_log_subjects 
ON ca_change_log_subjects.subject_row_id = ca_objects.object_id AND ca_change_log_subjects.subject_table_num = 57
INNER JOIN ca_change_log ON ca_change_log.log_id = ca_change_log_subjects.log_id
WHERE (ca_objects.object_id IN (5268,5353,5354,5355))  
AND ( (ca_objects.access IN (1)) AND (ca_objects.deleted = 0) 
AND ( ( (ca_change_log.log_datetime BETWEEN 1536616800 AND 1536789600) 
AND (ca_change_log.changetype IN ('I', 'U', 'D')))))

Adding a few variables to the select, (like this)
SELECT ca_objects.object_id, ca_change_log.log_datetime, ca_change_log.changetype, ca_change_log.logged_table_num
FROM ca_objects
INNER JOIN ca_change_log_subjects 
ON ca_change_log_subjects.subject_row_id = ca_objects.object_id AND ca_change_log_subjects.subject_table_num = 57
INNER JOIN ca_change_log ON ca_change_log.log_id = ca_change_log_subjects.log_id
WHERE (ca_objects.object_id IN (5268,5353,5354,5355))  
AND ( (ca_objects.access IN (1)) AND (ca_objects.deleted = 0) 
AND ( ( (ca_change_log.log_datetime BETWEEN 1536616800 AND 1536789600) 
AND (ca_change_log.changetype IN ('I', 'U', 'D')))))
it turned out that one of the returned objects was not of table 57 (ca_objects).

So I think it is necessary to add ca_change_log.logged_table_num = 57 to 
AND ( (ca_objects.access IN (1)) AND (ca_objects.deleted = 0) 
AND ( ( (ca_change_log.log_datetime BETWEEN 1536616800 AND 1536789600) 
AND (ca_change_log.changetype IN ('I', 'U', 'D')))) 

So taking BrowseEngine.php (in app/lib/ca/Browse), change line 2099 and 2174 in
$va_wheres[] = "(((ca_change_log.log_datetime BETWEEN ".(int)$va_range['start']." AND ".(int)$va_range['end'].") AND (ca_change_log.changetype IN ('I', 'U', 'D'))) AND ca_change_log.logged_table_num = " . $this->opn_browse_table_num . ")";

Can you try this?
@collectiveaccess Can you agree?

Anita

**Comment by aruijmen** [comment]
Hi @karbecker 
http://www.heron-net.be/ca_tudelft/service.php/OAI/dc_obj_erfgoed/request?verb=ListRecords&metadataPrefix=qdc&from=2018-09-11&until=2018-09-13
I would only define a date (without time) for from and until.

**Comment by collectiveaccess** [comment]
No this isn't correct. I'll take a closer look when I have time.

**Comment by collectiveaccess** [comment]
I've just committed a fixed OAI provider to the master-fix branch. If you drop the revised file (available here: https://github.com/collectiveaccess/providence/blob/0f87fe496ea4918369511e6d72f3ef6db79fd639/app/lib/ca/Service/OAIPMHService.php) into your 1.7.6 system it should work. I have tested this with 1.7.6. It should also work for 1.7.5.

The commit is here: https://github.com/collectiveaccess/providence/commit/0f87fe496ea4918369511e6d72f3ef6db79fd639

**Comment by aruijmen** [comment]
Hi @collectiveaccess an @karbecker 
You were right. This is not correct. 
In the record with another logged_table_num I actually deleted a ca_objects_x_collections relationship.  So it is normal that this record pops up. 
So forget what I said about changes to BrowseEngine.php

@karbecker
about your oai_provider.conf:
I think your schema and metadataNamespace need to be different for mets/generic and epicur
For mets:
- schema = http://www.loc.gov/standards/mets/mets.xsd
- metadataNamespace = http://www.loc.gov/METS/
For epicur 
- schema = http://www.persistent-identifier.de/xepicur/version1.0/xepicur.xsd
- metadataNamespace = urn:nbn:de:1111-2004033116
For generic: you can leave it.
(after a quick Google)

Using http://re.cs.uct.ac.za/ and http://validator.oaipmh.com/ 
you see you still have errors in verbs ListSets an ListIdentifiers 

I also find the ''setFacet = title_facet' strange.
Normally it points to a collection_facet (in browse.conf)

I send you my current oai_provider.conf and browse.conf to compare.

[local.zip](https://github.com/collectiveaccess/providence/files/2415425/local.zip)

**Comment by karbecker** [comment]
Thanks @collectiveaccess for the fix and thanks @aruijmen for your interest and for helping me correcting my oai_provider.conf! It all works now as I expect it to work 😊
