### ISSUE TITLE
Development cycle

### ISSUE THREAD

**Issue by miceno** [collectiveaccess/providence#434]
I suggest in the future all code should be developed in a branch from `develop`, tested and once it succeeds, merged into `develop`. It is more or less a git-flow workflow. That way others can also contribute to the branch and help on improving code quality.

Last changes like https://github.com/collectiveaccess/providence/commit/e4c51d267292324e954af082f66a0a287c78be55 or others broke `develop` to some extend, I mean, if tests don't pass, we should refactor and solve the issue.

I will prefer to have a `develop` branch that passes all tests and not broken. I consider `develop` is the canvas for other contributors to develop features, solve bugs, etc. A broken `develop` branch means others will not be able to contribute reliably to the project.

**Comment by collectiveaccess** [comment]
I agree. But it all requires more time (or more people) for that process to work. That has been the limiting factor here, and is a reason why things are often pushed to develop and sorted out once it's hits users who test on that branch.

I would welcome a return to the gitflow method. But it means either more people contributing or less development pressure. It's tough to balance these things.

We'll try tightening the process, because I don't think the current process is working as well as it could or should, and see if that can be made to work within the context of external demands.

**Comment by miceno** [comment]
Thank you!

It is a matter of time that the code will break if there are several developers onto it. Murphy's Law 😉 

I would not like to pressure on this, I would like just to start a conversation about how it will be the approach.

What about this "relaxed" workflow?

1. branch from `develop`
2. create your new code
3. test or break it as much as you need.
4. [optional] try to add test to make your new code more reliable.
5. ask for a PR. At least somebody else should review your changes.

I know the key is 5, and as you mentioned it is a matter of time, but from my experience, taking care of this is slower now, but makes code more robust and reliable. The other way code quality, technical debt, etc. will be problems that will appear every time.

At least, branching and PR will allow some traceability and isolation: while someone is developing a feature, others may safely branch from `develop`.

I tried to follow this practice while commiting code to this repo, and I think it is a successful approach. If I had commited code that didn't pass the test or it had any undefined variable or the like, code review and testing would have discovered it, before merging into develop.

As of now at step 5, Travis is giving us the answer to "is my code breaking something that worked before?", and I think it is important.

**Comment by collectiveaccess** [comment]
I don't think 4 is really optional but sometimes it has to be due to time constraints. I think at the least we will need to move to require at least some tests defined at the outset. Maybe they won't be perfect or cover enough, but a basic test will usually catch a lot. We have not been doing this to save time, but we'll change that.

Branching is important. For larger features that has always been done. For smaller work it has not been consistently done, which I agree is a mistake. We'll start doing that consistently.

Asking for PR's implies there's someone to review them. As of right now there may not be someone with time. That's a problem. We'll need to work on that, but there is no simple solution. That said, we'll give it a try and see how it works out.

**Comment by kehh** [comment]
We're happy to try and pick something up from that perspective as well (I know I've been quiet, but have been following this all quite avidly).

**Comment by collectiveaccess** [comment]
@kehh That would be incredibly helpful.

**Comment by miceno** [comment]
Hi!

I have seen a lot of new code committed to `develop`, but very few tests. Do you think we should consider it again enforcing tests before merging into `develop`?

I have seen projects grow in the past to the limit where new code started to break existing code and nobody realised till it was too late, I mean, when there was such a big amount of untested code that changing anything will start a cascade of side effects that will break the entire app.

I suggest we also try to refactor parts of the new code, to make it more robust and testable. For example, instead of adding the new code inline on existing code, encapsulate new code in a function, add a test for it and then integrate on the new code. This way technical debt will be reduced step by step. 

If every committer takes this into account, code quality will improve slowly without breaking big parts of the code.

It also requires that the project leader will suggest committers to improve code quality before accepting new code.

What do you think?

**Comment by miceno** [comment]
GIving up :(
