### ISSUE TITLE
Exporting relationship field to .docx brings up wrong image if multiple objects in relationship

### ISSUE THREAD

**Issue by jjs6791** [collectiveaccess/providence#996]
Say you have an entity relationship with two objects. object A has an image of a pencil and object B an image of a carrot.

You go into object B and related entity and export it to Word. It shows an image of a pencil (object A) instead of the expected carrot for object B .

on develop, last pull
https://github.com/collectiveaccess/providence/commits/44a8cba121f924e275ea94c85e1eb91fec2d3f30

**Comment by collectiveaccess** [comment]
Is this only in the Word export, or generally? Did it start recently, or has it been a persistent problem?

**Comment by collectiveaccess** [comment]
You are doing this from the summary screen of a record? If so, which record? Object A, Object B or the entity? I cannot reproduce this issue. If it's in the summary it may be due to an incorrectly written display template. If you jump a template from an object to an entity (for example) and then try to pull object fields, it'll be from the point of view of the entity and you'll get behavior like this.

**Comment by jjs6791** [comment]
Apologies, I am unable to replicate this
