### ISSUE TITLE
Edit conflict behaviour for checkbox fields not occurring

### ISSUE THREAD

**Issue by jjs6791** [collectiveaccess/providence#998]
Testing out a client's requirement to handle concurrent edits, or edit conflicts.

For text field, select fields and radio buttons the behaviour is as expected, with a slight inconstancy with select fields.  Details are written below.

However, with checkboxes, there is no warning of edit conflict.  I would expect that the behaviour would be the same as the other field types, even more so if the value of the specific input is changed via an edit conflict.

1) User A opens up object with preferred_label "Photograph" 
2) User B opens up the same object.
3) User A changes the preferred_label to "Photograph 1" and submits the form.  The save occurs.
4) User B changes the preferred_label to "Photograph 2" and submits the form.  The message "Changes have been made since you loaded this data by CollectiveAccess Administrator (foo@emailaddress.com). Save again to overwrite the changes or cancel to keep the changes."
5) The text of the preferred_label updated to "Photograph 1", reflecting the current value
6) At this point, as reflected in the message the user can leave the item alone, or save.
7) User B proceeds to change the preferred_label to "Photograph 2" again.  User B has to duplicate efforts in changing the label again, but this way they are able to review the most recent change.
8) Now the preferred_label of "Photograph 2" saves and is the new value.

A select is slightly not consistent with a text field: with step 5 above, on first save for user B it does not show the most recent value by user A.  However, there is still the opportunity to save with the latest change.

**Comment by collectiveaccess** [comment]
Is this actually a problem?

**Comment by jjs6791** [comment]
If it fires on other input types, shouldn't it fire on checkboxes as well?

**Comment by collectiveaccess** [comment]
Ok, I see what you're talking about now. 

For repeating fields, conflict detection takes place at the value level, not for overall field. If you've got a repeating text field (for example) with a value in it, a conflict will fire if two users try to edit the same value at the same time, but if they each add or delete values to the field no conflict will be triggered. The intention is to prevent one user from inadvertently overwriting text from another user, rather than preventing all simultaneous access.

For checklists, each user's save adds or deletes discrete values, but users are never actually _editing_ the same values so conflicts don't trigger. Repeating fields using drop-down lists work similarly, except that since there's also the opportunity to change the value in-place a conflict _can_ be triggered if two users change the selected option in an existing value. If user only add or delete drop-down list values, rather than changing existing selections, no conflict will trigger.

I can understand the argument for triggering a conflict for  _any_ change made to a field in the time since the form was loaded, but the current implementation tries to restrict conflicts to situations where data may be lost by operating at value-level. It assumes that cataloguers are not working at cross-purposes.

It'd be possible to change this behavior if it's critical to someone, but we've not received much feedback, good or bad, about the current implementation, which has been around for ~10 years now.

**Comment by jjs6791** [comment]
Thank you for the explanation.  I think the behavior is good for providing a simple resolution for edit conflicts.   I'll see how the client goes with it and let you know if they require more aggressive conflict handling.
